home:
    path:     /
    defaults: { _controller: OCArticleBundle:Advert:afficher }

articleafficher2:
    path:     /afficher/{id}
    defaults: { _controller: OCArticleBundle:Advert:afficher2 }


articlemodifier:
    path:     /modifier/{id}
    defaults: { _controller: OCArticleBundle:Advert:modifier }

articlesupprimer:
    path:     /supprimer/{id}
    defaults: { _controller: OCArticleBundle:Advert:supprimer }


articleajouter:
    path:     /ajouter
    defaults: { _controller: OCArticleBundle:Advert:ajouter }

formulaire:
    path:     /afficherformulaire
    defaults: { _controller: OCArticleBundle:Advert:afficherformulaire }

boxoffice:
    path:     /boxoffice
    defaults: { _controller: OCArticleBundle:Advert:boxoffice }

test:
    path:     /test
    defaults: { _controller: OCArticleBundle:Advert:test }
