articleafficher1:
    path:     /afficher
    defaults: { _controller: OCArticleBundle:Advert:afficher }

articleafficher2:
    path:     /afficher2
    defaults: { _controller: OCArticleBundle:Advert:afficher2 }

articleafficher3:
    path:     /afficher3
    defaults: { _controller: OCArticleBundle:Advert:afficher3 }

articleaccueil:
    path:     /accueil
    defaults: { _controller: OCArticleBundle:Advert:accueil}


articlemodifier:
    path:     /modifier
    defaults: { _controller: OCArticleBundle:Advert:modifier }

articlesupprimer:
    path:     /supprimer
    defaults: { _controller: OCArticleBundle:Advert:supprimer }

articleajouter:
    path:     /ajouter
    defaults: { _controller: OCArticleBundle:Advert:ajouter }

formulaire:
    path:     /afficherformulaire
    defaults: { _controller: OCArticleBundle:Advert:afficherformulaire }

boxoffice:
    path:     /boxoffice
    defaults: { _controller: OCArticleBundle:Advert:boxoffice }


