articleafficher:
    path:     /afficher
    defaults: { _controller: OCArticleBundle:Advert:afficher }

articleaccueil:
    path:     /accueil
    defaults: { _controller: OCArticleBundle:Advert:accueil}


articlemodifier:
    path:     /modifier
    defaults: { _controller: OCArticleBundle:Advert:modifier }

articlesupprimer:
    path:     /supprimer
    defaults: { _controller: OCArticleBundle:Advert:supprimer }

articleajouter:
    path:     /ajouter
    defaults: { _controller: OCArticleBundle:Advert:ajouter }

formulaire:
    path:     /afficherformulaire
    defaults: { _controller: OCArticleBundle:Advert:afficherformulaire }



